# Generated by Django 4.1.1 on 2022-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical', '0003_alter_historical_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
