# Generated by Django 4.1.1 on 2022-12-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical', '0007_rename_fields_historical_post_historical_pre'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='field_updated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
